name: babyprediction
publish_to: 'none'
version: 1.0.7+19

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  dio: ^5.3.3
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  another_flutter_splash_screen: ^1.2.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  purchases_flutter: ^6.30.1
  modal_progress_hud_nsn: ^0.5.1
  uuid: ^4.4.2
  url_launcher: ^6.3.0
  go_router: ^14.2.1
  launch_review: ^3.0.1
  gallery_saver: ^2.3.2
  flutter_riverpod: ^2.6.1
  image_gallery_saver: ^2.0.3
  lottie: ^3.0.0
  flutter_dotenv: ^5.1.0
  smooth_page_indicator: ^1.1.0
  in_app_review: ^2.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700